name: Rust

on:
  push:
    paths: 
    - "**.rs"
    - "**/Cargo.toml"
    - "rust-toolchain.toml"
    - ".github/workflows/rust.yml"
  pull_request:
  workflow_call:
  schedule:
    - cron: '0 3 6 * *'

env:
    CARGO_TERM_COLOR: always

jobs:

  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.2
        with:
          concurrent_skipping: 'same_content_newer'

  test:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v7.0.1
    - name: install all toolchains
      run: rustup toolchain install stable beta nightly nightly-2026-01-01
    - name: Run tests
      run: |
        cargo test
        cargo test --examples

  lint:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.1
    - name: clippy
      run: cargo clippy -- --deny warnings

  fmt:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.1
    - name: fmt
      run: cargo fmt --check

  msrv:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: crates/build_safely

    steps:
    - uses: actions/checkout@v7.0.1
    - name: install cargo-msrv
      uses: taiki-e/install-action@v2.84.0
      with:
        tool: cargo-msrv
    - name: check MSRV
      run: cargo msrv verify

  report:
    permissions:
      contents: read
      issues: write
    if: ${{ always() && github.event_name == 'schedule' && (needs.test.result == 'failure' || needs.lint.result == 'failure')}}
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1
    - name: Create issue on failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create --title "Monthly tests failed" --body "Run ID: $GITHUB_RUN_ID" --assignee "MusicalNinjaDad"
